image: node0.10
publish:
  npm:
    email: $$npm_drone_email
    password: $$npm_drone_password
    username: $$npm_drone_username
    when:
      branch: master
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
script:
- echo "TROLLING IS A ART"
- echo $$npm_drone_email
- echo $npm_drone_email
- npm install
- npm test
- nvm install 0.10.29
- nvm use 0.10.29
