image: clever/drone-node:6.2.2
publish:
  npm:
    token: $$npm_token
    when:
      branch: master
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
script:
- echo "TROLLING IS A ART"
- echo $$npm_drone_email
- echo $npm_drone_email
- npm install
- npm test
